### ISSUE TITLE
Telegram channel doesn't exist

### ISSUE THREAD

**Issue by RazcoDev** [Andrey-Anatolyevich/UsaVisaInterviewDateNotifier#2]
Hey, unfortunately telegram channel doesn't exist. 

any updated about that ? 
@Andrey-Anatolyevich

**Comment by zTechSoul** [comment]
Yeah.
Due to no interest from public I decided to take down the application and stop paying for a server which it was running on.

Sorry for inconvenience. Will update README

**Comment by Jilda1987** [comment]
Hi so this not working ???

**Comment by zTechSoul** [comment]
> Hi so this not working ???

No, it is not working.
I stopped the server due to extreme low interest.
The bot and the support group are removed.
